5-djangoTest/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    #DICE: QUANDO QUALCUNO DIGITA http://www.localhost/8000/polls/ PER SAPERE CHE URL (E QUINDI QUALE PAG) VAI AL FILE urls.py DENTRO POLLS
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

5-djangoTest/mysite/polls/urls.py
from django.urls import path

from . import views #perchè richiamiamo le funzioni che definiamo nelle view

app_name = 'polls'
urlpatterns = [
    #VUOL DIRE: SE QUALCUNO VA SUL NOSTRO SITO CHE SI CHIAMA, PER ESEMPIO, ELENA.COM, SENZA NIENTE (QUINDI SOLO ELENA.COM) VIENE INDIRIZZATO DALLA FUNZIONE INDEX DEL FILE VIEWS
    #NEL NOSTRO CASO: http://www.localhost:8000/polls/ SENZA NIENTE CHE SEGUE POLLS
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

5-djangoTest/mysite/polls/models.py
from django.db import models

# Create your models here.
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

5-djangoTest/mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .models import Choice, Question

#per importare template html
from django.template import loader
#per shortcut con render
from django.shortcuts import get_object_or_404, render

from django.urls import reverse
from django.views import generic
#per gestione err 404
from django.http import Http404

from django.utils import timezone
#mi serve per il controllo pubblicazione domande che NON sia futura

#PRIMA
#LA FUNZIONE DICE CHE PAGINA VISUALIZZARE QUANDO VADO ALL'HOMEPAGE
#PER MAPPARE OGNI VISTA CON UNO SPECIFICO URL (NEL NOSTRO CASO http://localhost:8000/polls/)
#SERVE SPECIFICARLO NEL FILE url.py SEMPRE IN QUESTA CARTELLA, E IN urls.py CONTENUTO
#NELLA CARTELLA mysite/mysite


#DOPO:
#gestione con generic view

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """

        #__lte è una funzione usata per le datetime: datetimeinput__lte = altra_data
        #che permette di confrontare che datetimeinput sia precedente o uguale a altra_data
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

#in queste f come parametro passo anche question_id, perchè riferiscono a uno specifico el del db
#mentre il parametro request esiste sempre in qualsiasi richiesta!!


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.

        Deve escludere domande con date di pubblicazione non ammissibili (futuro)
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

#si arriva a questa vista quando seleziono una choice da vote
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

#funzione per votare la risposta alla domanda
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        #request.POST è un oggetto simile a un dictionary che permette di accedere ai dati
        #che confermo (in questo caso la scelta) attraverso la pk.
        #In questo caso request.POST['choice']  ritorna l'id della choice selezionata
        #come una stringa, dal momento che request.POST ha come valori sempre stinghe
        #volendo ci sarebbe la possibilità di fare la stessa azione con GET, ma noi la
        #facciamo con la POST perchè andiamo a modificare i dati nel MOdel

        #request.POST['choice']  è messa in un blocco try perchè lancia un errore se
        #l'utente non seleziona alcuna choice da fornire alla POST (quindi caso in cui
        #preme solo il bottone di conferma scelta senza realmente scegliere)
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        #se tutto va bene aumento il count della choice, perchè un utente in più
        #l'ha scelta
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.


        #Invece di una solita HttpResponse uso HttpResponseRedirect, che prende
        #come argomento l'URL al quale l'utente viene inviato
        #Come sottolineato nel commento Python sopra, dovresti sempre restituire un
        # HttpResponseRedirect dopo aver gestito correttamente i dati POST.
        # Questo suggerimento non è specifico di Django; è una buona pratica di sviluppo Web in generale.


        '''
        COSA SUCCEDE NEL RETURN:
            -Il costruttore di HttpResponseRedirect prende un solo argomento: URL dove l'utente è reindirizzato
            -Tale argomento qui viene gestito con la funzione reverse(). La funzione serve a evitare di avere l'URL
             hard-coded nella funzione. A tale funzione serve il nome della view alla quale voglio passare il controllo
             e la parte variabile del pattern URL che punta a quella vista.
             Nel nostro caso, usando urlconf prima settato, la funzione reverse creerà una stringa del tipo:
             /polls/3/results/
             dove 3 è il valore di una question.id
        '''
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

5-djangoTest/mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<!--
LA SEGUENTE PAGINA VISUALIZZA UN BOTTONE RADIO PER OGNI OPZIONE DELLA DOMANDA
IL VALORE DEL BOTTONE RADIO E' ASSOCIATO ALLA ID DELLA QUESTION
il name="choice" pr l'input, sta  a indicare che quando qualcuno seleziona il
radio botton e ne fa il submit del form, invierà un richiesta POST
con choice=#, con # id della choice selezionata (questo è il concetto base dell'HTML)

con form action=" url 'polls:vote' question.id  method="post" metto POST perchè
la submit di questa azione altera i dati all'interno del model server-side.
QUINDI OGNI VOLTA CHE CREO UNA FORM CHE ALTERA I DATI  PER SEMPRE SEMPRE METODO POST
questa è buona pratica in generale

forloop.counter indica quante volte il tag for ha attraversato il suo ciclo

Poiché stiamo creando un modulo POST (che può avere l'effetto di modificare i dati),
dobbiamo preoccuparci dei falsi delle richieste tra siti. Per fortuna, non devi
preoccuparti troppo, perché Django ha un sistema utile per proteggerti.
In breve, tutti i moduli POST destinati agli URL interni devono utilizzare il tag
modello  csrf_token.


-->
<body>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>
</body>
</html>

5-djangoTest/mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>
<!--COSA FA IL CODICE:
if latest_question_list  == se esiste una lista di domanda, allora creo una lista non ordinara (ul)
                                 i cui elementi sono presi da un ciclo for di python che scorre la collezione di domande
else : allra dico che non esistono domande
NOTARE CHE I COMANDI PYTHON NEL CODICE HTML SONO CONTENUTI IN graffe+segno percentule (NON POSSO SCRIVERLO ESPLICITAMENTE SE NO DA ERRORE LOL)

La variabile latest_question_list viene passata al file HTML attraverso il parametro context nella f in views.py, all'interno
della funzione render di renturn. Il context quindi serve per passare tutte le var del db/python che servono per l'elaborazione HTML
Infatti la var context in views.py è un dictionary che associa un nome (che verrà utilizzato nel HTML per riferirsi a quella
specifica var) alla var che voglio passare

-->
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!--LINK HARD-CODED, MENO BELLO:
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
        -->
        <!--LINK DINAMICO-->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

5-djangoTest/mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>